# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: luminous-api Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Container
    
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://luminouscr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_eb3fffa38f4a4dcf98fec3594dd7d537 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a699b7c600854857935ee2dfba5eb71f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: luminouscr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eb3fffa38f4a4dcf98fec3594dd7d537 }}/luminous-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    name: Deploy Docker Container
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'luminous-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_637996126cb146b193df3d0bae471167 }}
        images: 'luminouscr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eb3fffa38f4a4dcf98fec3594dd7d537 }}/luminous-api:${{ github.sha }}'